server:
  port: 3030

mywx:
  appID: wx7a9819472a57d7fb
  appsecret: ac8a75e43b68dbe1f41899a3c33f1b9c
  #天气模板id
  tempateid1: PXn5RpfdiH4A7CjvIjAwBMAtnK0I3gsfIPzMsNn9VEc
  #时间模板id
  tempateid2: pg97vEMvP28EznTg-o7pv30GMarH14MQlsfeN2vqB7k
  #事件提醒
  tempateid3: mlJoQLo-wbeNphfj4vwRHLDL1nCUWBYDyvSEyH3GI0A
  #城市id，这个id自己去网上找对应的城市id。https://yikeapi.com/help/tianqicity
  cityid: 101041700
  #认识的日子
  day1: 2002-10-24
  #在一起的日子
  day2: 2001-12-24
  #我的生日
  day3: 2002-04-02
  #宝贝生日
  day4: 2002-02-04
  #要推送的用户列表
  users:
    - oaQlR6aBJcuxijJG-i58cAS3ngxM
    - 用户id
